### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpServer#36]
MySQL server has gone away
```
2020-04-01T20:18:15.286475350Z [2020-04-01 20:18:15,266] ERROR in app: Exception on /rebabel/who_is_online [GET]
2020-04-01T20:18:15.286540421Z Traceback (most recent call last):
2020-04-01T20:18:15.286549630Z   File "/usr/local/lib/python3.8/site-packages/flask_sockets.py", line 40, in __call__
2020-04-01T20:18:15.286555279Z     handler, values = adapter.match()
2020-04-01T20:18:15.286560149Z   File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 1945, in match
2020-04-01T20:18:15.286565334Z     raise NotFound()
2020-04-01T20:18:15.286570547Z werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2020-04-01T20:18:15.286576117Z 
2020-04-01T20:18:15.286580717Z During handling of the above exception, another exception occurred:
2020-04-01T20:18:15.286585362Z 
2020-04-01T20:18:15.286589937Z Traceback (most recent call last):
2020-04-01T20:18:15.286594430Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
2020-04-01T20:18:15.286599554Z     self.dialect.do_execute(
2020-04-01T20:18:15.286604124Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
2020-04-01T20:18:15.286609217Z     cursor.execute(statement, parameters)
2020-04-01T20:18:15.286614034Z   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
2020-04-01T20:18:15.286619230Z     res = self._query(query)
2020-04-01T20:18:15.286624040Z   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
2020-04-01T20:18:15.286628697Z     db.query(q)
2020-04-01T20:18:15.286633087Z   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
2020-04-01T20:18:15.286637939Z     _mysql.connection.query(self, query)
2020-04-01T20:18:15.286642552Z MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')
2020-04-01T20:18:15.286647562Z 
2020-04-01T20:18:15.286651822Z The above exception was the direct cause of the following exception:
2020-04-01T20:18:15.286656312Z 
2020-04-01T20:18:15.286660574Z Traceback (most recent call last):
2020-04-01T20:18:15.286665457Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
2020-04-01T20:18:15.286670280Z     response = self.full_dispatch_request()
2020-04-01T20:18:15.286674742Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
2020-04-01T20:18:15.286695069Z     rv = self.handle_user_exception(e)
2020-04-01T20:18:15.286699492Z   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
2020-04-01T20:18:15.286703644Z     return original_handler(e)
2020-04-01T20:18:15.286707567Z   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
2020-04-01T20:18:15.286711694Z     return original_handler(e)
2020-04-01T20:18:15.286716582Z   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
2020-04-01T20:18:15.286720963Z     return original_handler(e)
2020-04-01T20:18:15.286724882Z   [Previous line repeated 1 more time]
2020-04-01T20:18:15.286728782Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
2020-04-01T20:18:15.286733072Z     reraise(exc_type, exc_value, tb)
2020-04-01T20:18:15.286736979Z   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
2020-04-01T20:18:15.286741254Z     raise value
2020-04-01T20:18:15.286745209Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
2020-04-01T20:18:15.286749359Z     rv = self.dispatch_request()
2020-04-01T20:18:15.286753277Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
2020-04-01T20:18:15.286757540Z     return self.view_functions[rule.endpoint](**req.view_args)
2020-04-01T20:18:15.286761532Z   File "/app/warpserver/server.py", line 46, in rebabel_who_is_online
2020-04-01T20:18:15.286765696Z     for user in User.query:
2020-04-01T20:18:15.286769732Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3403, in __iter__
2020-04-01T20:18:15.286774036Z     return self._execute_and_instances(context)
2020-04-01T20:18:15.286777979Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3428, in _execute_and_instances
2020-04-01T20:18:15.286782253Z     result = conn.execute(querycontext.statement, self._params)
2020-04-01T20:18:15.286786251Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 984, in execute
2020-04-01T20:18:15.286790438Z     return meth(self, multiparams, params)
2020-04-01T20:18:15.286794351Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
2020-04-01T20:18:15.286798562Z     return connection._execute_clauseelement(self, multiparams, params)
2020-04-01T20:18:15.286802568Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_clauseelement
2020-04-01T20:18:15.286839848Z     ret = self._execute_context(
2020-04-01T20:18:15.286845271Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1287, in _execute_context
2020-04-01T20:18:15.286856636Z     self._handle_dbapi_exception(
2020-04-01T20:18:15.286860794Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _handle_dbapi_exception
2020-04-01T20:18:15.286865039Z     util.raise_(
2020-04-01T20:18:15.286869401Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
2020-04-01T20:18:15.286873578Z     raise exception
2020-04-01T20:18:15.286877522Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
2020-04-01T20:18:15.286881799Z     self.dialect.do_execute(
2020-04-01T20:18:15.286886668Z   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
2020-04-01T20:18:15.286890996Z     cursor.execute(statement, parameters)
2020-04-01T20:18:15.286894971Z   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
2020-04-01T20:18:15.286899278Z     res = self._query(query)
2020-04-01T20:18:15.286903304Z   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
2020-04-01T20:18:15.286907444Z     db.query(q)
2020-04-01T20:18:15.286911939Z   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
2020-04-01T20:18:15.286918599Z     _mysql.connection.query(self, query)
2020-04-01T20:18:15.286924889Z sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2006, 'MySQL server has gone away')
2020-04-01T20:18:15.286933436Z [SQL: SELECT users.id AS users_id, users.date_created AS users_date_created, users.date_modified AS users_date_modified, users.username AS users_username, users.password_hash AS users_password_hash, users.email AS users_email, users.power AS users_power, users.note AS users_note, users.locked AS users_locked 
2020-04-01T20:18:15.286940779Z FROM users]
```

Apparently there is a Timeout issue with the MySQL Server.

**Comment by KeyboardInterrupt** [comment]
As a first Test, lets crank up the Wait timeout to: `--wait_timeout=57600`
:shrug:
